[package]
name = "Neuron"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
riven = ">=2.50.0"

[dependencies]
redb = "~2.1"
riven = "~2.50"
tokio = { version = "~1.37", features = ["rt", "macros", "signal"] }
anyhow = "~1.0"
clap = { version = "~4.5", features = ["default", "derive"] }
base64 = "~0.22"

[dev-dependencies]
rand = "~0.8"