[package]
name = "Neuron"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
reqwest = { version = "^0.12.4", features = ["blocking"] }
regex = "^1.10.4"

[dependencies]
redb = "^2.1.0"
riven = "^2.50"
tokio = { version = "^1.37", features = ["rt", "macros", "signal"] }
anyhow = "^1.0.86"
clap = { version = "^4.5.4", features = ["default", "derive"] }
base64 = "^0.22.1"